const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Keyboard.Cnds.OnAnyKey
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{nave1: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{tiro1: 0},
	{PlanoDeFundoFase1: 0},
	{Âncora: 0},
	{PlanoDeFundoInicio: 0},
	{tituloinicio: 0},
	{naveinicio: 0},
	{inicio: 0},
	{btnJogar: 0},
	{metazul1: 0},
	{metazul2: 0},
	{metcnz1: 0},
	{metver1: 0},
	{PlanoDeFundoFase2: 0},
	{vidaig1: 0},
	{inim1: 0},
	{tiroig1: 0},
	{barravidahero: 0},
	{Browser: 0},
	{barravidaig: 0},
	{barravidaig2: 0},
	{vidaig4: 0},
	{inim4: 0},
	{PlanoDeFundoGOver: 0},
	{tiroig4: 0},
	{TextoGOver: 0},
	{naveGO: 0},
	{reiniciar: 0},
	{Áudio: 0}
];

self.InstanceType = {
	nave1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	tiro1: class extends self.ISpriteInstance {},
	PlanoDeFundoFase1: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoInicio: class extends self.ITiledBackgroundInstance {},
	tituloinicio: class extends self.ITextInstance {},
	naveinicio: class extends self.ISpriteInstance {},
	inicio: class extends self.ISpriteFontInstance {},
	btnJogar: class extends self.ISpriteFontInstance {},
	metazul1: class extends self.ISpriteInstance {},
	metazul2: class extends self.ISpriteInstance {},
	metcnz1: class extends self.ISpriteInstance {},
	metver1: class extends self.ISpriteInstance {},
	PlanoDeFundoFase2: class extends self.ITiledBackgroundInstance {},
	inim1: class extends self.ISpriteInstance {},
	tiroig1: class extends self.ISpriteInstance {},
	barravidahero: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	barravidaig: class extends self.ISpriteInstance {},
	barravidaig2: class extends self.ISpriteInstance {},
	inim4: class extends self.ISpriteInstance {},
	PlanoDeFundoGOver: class extends self.ITiledBackgroundInstance {},
	tiroig4: class extends self.ISpriteInstance {},
	TextoGOver: class extends self.ITextInstance {},
	naveGO: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ISpriteFontInstance {},
	Áudio: class extends self.IInstance {}
}