const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{nave1: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{tiro1: 0},
	{tiro2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Âncora: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{tituloinicio: 0},
	{naveinicio: 0},
	{inicio: 0},
	{btnJogar: 0},
	{metazul1: 0},
	{metazul2: 0},
	{metcnz1: 0},
	{metver1: 0},
	{armadura: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{vidaig1: 0},
	{inim1: 0},
	{tiroig1: 0},
	{Anchor: 0},
	{barravidahero: 0},
	{Browser: 0},
	{barravidaig: 0},
	{vidaig2: 0},
	{inim2: 0},
	{tiroig2: 0},
	{barravidaig2: 0}
];

self.InstanceType = {
	nave1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	tiro1: class extends self.ISpriteInstance {},
	tiro2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	tituloinicio: class extends self.ITextInstance {},
	naveinicio: class extends self.ISpriteInstance {},
	inicio: class extends self.ISpriteFontInstance {},
	btnJogar: class extends self.ISpriteFontInstance {},
	metazul1: class extends self.ISpriteInstance {},
	metazul2: class extends self.ISpriteInstance {},
	metcnz1: class extends self.ISpriteInstance {},
	metver1: class extends self.ISpriteInstance {},
	armadura: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	inim1: class extends self.ISpriteInstance {},
	tiroig1: class extends self.ISpriteInstance {},
	barravidahero: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	barravidaig: class extends self.ISpriteInstance {},
	inim2: class extends self.ISpriteInstance {},
	tiroig2: class extends self.ISpriteInstance {},
	barravidaig2: class extends self.ISpriteInstance {}
}